# Generated by Django 4.2.1 on 2023-06-01 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_band_fk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='band',
            old_name='official_fomepage',
            new_name='official_homepage',
        ),
    ]
