# Generated by Django 4.2.1 on 2023-06-01 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_rename_official_fomepage_band_official_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='band_fk',
            new_name='band',
        ),
    ]
